### ISSUE TITLE
Add schedule metaparameter support to the "ohmyzsh::git upgrade ${name}" resource

### ISSUE THREAD

**Issue by divansantana** [zanloy/puppet-ohmyzsh#4]
For performance reasons (and other reasons) would be best not to check for upgrades for each user on every puppet run. Therefore one can use the schedule metaparameter to only check for updates once a day. I do this with the Exec override though currently I have to specify the username like so:

```
    ohmyzsh::upgrade { 'user1': }
    Exec <| title == 'ohmyzsh::git upgrade user1' |> {
      schedule => 'everyday',
    }
```

Would be nice if could specify the schedule in the ohmyzsh::upgrade class like so:

```
    ohmyzsh::upgrade { 'user1': }
    frequency => 'everyday',
```

**Comment by zanloy** [comment]
I'm going to close this because since schedule is a metaparameter, it can be applied to the entire class. Thus:

``` puppet
ohmyzsh::update { 'user1': schedule => 'daily' }
```

Will have the same intended purpose. The ::upgrade class only has a single Exec anyways.

I have updated the README though to include this nice tip because you are right, it is silly to poll github every check-in. I wanted to make the ::update class default to schedule => 'daily' but it gave me a warning that I could not dismiss programmatically so I just put it in the documentation.

**Comment by divansantana** [comment]
Thanks!
